### 1. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.

In [92]:
total_sum = 0
for i in range(1,1000):
    if i %3 == 0 or i %5 ==0:
        total_sum += i
print(total_sum)

233168

### 2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [89]:
a,b = 1,1
total = 0
while (a < 4000000):
    a,b = b, a+b
    if a%2 == 0:
        total += a
print(total)

4613732

### 3. The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143 ?

In [128]:
def lpf(x):
    lpf=2
    while (x>lpf):
        if (x%lpf==0):
            x=x/lpf
            print(x)
            print('*')
        else:
            lpf = lpf+1
            print(lpf)
    return x
print(lpf(42))

21.0
*
3
7.0
*
4
5
6
7
7.0

### 4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers

In [133]:
pal = []
for i in range(100, 1000):
    for j in range(100, 1000):
        prod = str(i*j)
        if prod == prod[::-1]:
            pal.append(int(prod))
print(max(pal))

906609

In [67]:
def insert_sort(original_list):
    new_list = original_list
    for i in range(len(original_list)):
        j = i
        while j > 0 and new_list[j-1] > new_list[j]:
            new_list[j-1], new_list[j] = new_list[j], new_list[j-1]
            #Reduce J by 1
            j = j-1
    return new_list

In [68]:
import time
import random

random.seed(a = 100)
short_list = list(random.sample(range(1000000), 10))
long_list = list(random.sample(range(1000000), 10000))

In [69]:
#start the time
start_time = time.time()

insert_sort(long_list)

print('------ %s seconds------' % (time.time() - start_time))

------ 11.481016874313354 seconds------

In [51]:
# start the time
start_time = time.time()

insert_sort(short_list)

print('---- %s seconds -----' % (time.time()-start_time))
print(insert_sort(short_list))

---- 0.0001010894775390625 seconds -----
[152745, 183236, 366725, 412125, 477025, 481850, 739784, 767514, 808225, 997948]

In [71]:
start_time = time.time()

sorted(long_list)
print('--- %s seconds ----' % (time.time()- start_time))

--- 0.00042319297790527344 seconds ----

### 5. 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [28]:
def prime(num):
    for i in range(1, num):
        if num > 1:
            if (num %i) == 0:
                break
            else:
                print(num)

In [29]:
prime(11)

In [30]:
from fractions import gcd
def lcm(a,b):
    "Calculate the lowest common multiple of two integers a and b"
    return a*b//gcd(a,b)

In [34]:
print(reduce(lcm, range(1,11)))
print(reduce(lcm, range(1,21)))

2520
232792560

/Users/krishnadevabhaktuni/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  after removing the cwd from sys.path.

### 6. The sum of the squares of the first ten natural numbers is,12+22+...+102=385 The square of the sum of the first ten natural numbers is, (1+2+...+10)2=552=3025 Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025−385=2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [158]:
x = list(np.arange(1,101,1))

In [159]:
squares = []
for i in x:
    a = (i*i)
    squares.append(a)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

In [142]:
def sum_of(x):
    total = 0
    for i in range(1, x):
        total = total+i
    return total**2

In [146]:
square_of_sum =  sum_of(101)
square_of_sum

25502500

In [154]:
total1 =0
for i in squares:
    total1 = total1+i
print(total1)

338350

In [155]:
ans = square_of_sum - total1
ans

25164150

### 7. By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?

In [8]:
def prime_num(num):
    for i in range(2, num):
        if num % i == 0:
            break
    else:
        print(num)

In [9]:
for num in range(2, 100):
    print(prime_num(num))

2
None
3
None
None
5
None
None
7
None
None
None
None
11
None
None
13
None
None
None
None
17
None
None
19
None
None
None
None
23
None
None
None
None
None
None
29
None
None
31
None
None
None
None
None
None
37
None
None
None
None
41
None
None
43
None
None
None
None
47
None
None
None
None
None
None
53
None
None
None
None
None
None
59
None
None
61
None
None
None
None
None
None
67
None
None
None
None
71
None
None
73
None
None
None
None
None
None
79
None
None
None
None
83
None
None
None
None
None
None
89
None
None
None
None
None
None
None
None
97
None
None
None

In [60]:
import time
def get_primes(n):

    start_time = time.time()
    numbers = set(range(n, 1, -1))
    primes = []
    while numbers:
        p = numbers.pop()
        primes.append(p)
        numbers.difference_update(set(range(p*2, n+1, p)))
    end_time = time.time()
    print('Time taken: %0.5f'%(end_time- start_time) )   
    return primes
x = get_primes(2000000)

Time taken: 1.12806

In [61]:
print(sum(x))

142913828922

In [252]:
print(x[-1], end ='')

104743

In [11]:
def add(*args):
    s = sum(args)
    return(s)
add(2,3,45,64)

114

### 9 A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a^2 + b^2 = c^2 For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2. There exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc.|

In [39]:
def triplet():
    for a in range(1, 1000):
        for b in range(100, 1000):
            c = (1000-a-b)
            if (a**2 + b**2 == c**2):
                return (a,b,c), (a*b*c)

In [40]:
triplet()

((200, 375, 425), 31875000)

### 8 The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [63]:
s = "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450"

In [78]:
largestproduct = 0
for i in range(0, len(s)-13):
    product = 1
    for j in range(i, i+13):
        product = product * int(s[j:j+1])
        if product > largestproduct:
            largestproduct = product
print(largestproduct)

23514624000

In [77]:
largestProduct = 0

for i in range(0, len(s) - 13):

    product = 1

    for j in range(i, i + 13):
        product *= int(s[j: j + 1])

    if product > largestProduct:
        largestProduct = product

print (largestProduct)

23514624000